name: CI

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Get latest Luau version
        id: get_latest
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/Roblox/luau/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Download Luau binary
        run: |
          echo "Downloading Luau version $LATEST_TAG"
          curl -LO https://github.com/Roblox/luau/releases/download/${LATEST_TAG}/luau-linux
          file luau-linux
          chmod +x luau-linux
          sudo mv luau-linux /usr/local/bin/luau

      - name: Verify Luau installation
        run: luau --version
        