name: CI

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest Luau version
        id: get_latest
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repositories/148821256/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Download Luau binary
        run: |
          echo "Downloading Luau version ${{ env.LATEST_TAG }}"
          curl -LO https://github.com/luau-lang/luau/releases/download/${{ env.LATEST_TAG }}/luau-ubuntu.zip
          unzip luau-ubuntu.zip
          chmod +x luau
          sudo mv luau /usr/local/bin/luau

      - name: Verify Luau installation
        run: luau-analyze --version
        