name: CI

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Luau Version
        id: get_latest
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repositories/148821256/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Luau Cache
        id: cache-luau
        uses: actions/cache@v4
        with:
          path: luau-binaries
          key: luau-${{ env.LATEST_TAG }}
          restore-keys: luau-
          save-always: true

      - name: Debug cache hit
        run: echo "Cache hit? ${{ steps.cache-luau.outputs.cache-hit }}"

      - name: Setup Luau (If Cached)
        if: steps.cache-luau.outputs.cache-hit == 'true'
        run: |
          echo "Luau cache hit, copying binaries"
          ls luau-binaries
          sudo cp luau-binaries/luau /usr/local/bin/luau
          sudo cp luau-binaries/luau-analyze /usr/local/bin/luau-analyze
          sudo cp luau-binaries/luau-ast /usr/local/bin/luau-ast
          sudo cp luau-binaries/luau-compile /usr/local/bin/luau-compile

      - name: Setup Luau (If Not Cached)
        if: steps.cache-luau.outputs.cache-hit != 'true'
        run: |
          echo "Downloading Luau version ${{ env.LATEST_TAG }}"
          mkdir -p luau-binaries
          curl -L -o luau-binaries/luau-ubuntu.zip https://github.com/luau-lang/luau/releases/download/${{ env.LATEST_TAG }}/luau-ubuntu.zip
          unzip luau-binaries/luau-ubuntu.zip -d luau-binaries/
          chmod +x luau-binaries/luau luau-binaries/luau-analyze luau-binaries/luau-ast luau-binaries/luau-compile
          sudo cp luau-binaries/luau /usr/local/bin/luau
          sudo cp luau-binaries/luau-analyze /usr/local/bin/luau-analyze
          sudo cp luau-binaries/luau-ast /usr/local/bin/luau-ast
          sudo cp luau-binaries/luau-compile /usr/local/bin/luau-compile

      - name: Run Tests
        run: |
          perl -pi -e 's/require\("\@self"\)/require\("\.\/"\)/g' src/init.test.luau
          output=$(luau-analyze src/init.test.luau --fflags=LuauSolverV2,true)
          if [ -n "$output" ]; then
            echo "$output"
            echo "luau-analyze found issues!"
            exit 1
          fi
        